# Generated by Django 3.2.8 on 2021-10-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='auction_bidder_comments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_bids',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_comments',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_reserve',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_seller',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_views',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auction_watchers',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='bike_location',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='bike_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='auction_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bids',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='auction_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_votes',
            field=models.IntegerField(),
        ),
    ]
