# Generated by Django 3.2.8 on 2021-10-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211012_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='auction_end',
        ),
        migrations.RemoveField(
            model_name='auctions',
            name='auction_start',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='bid_datetime',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_datetime',
        ),
    ]
