# Generated by Django 3.2.8 on 2021-10-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211012_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid_amount',
            field=models.CharField(max_length=64),
        ),
    ]
