# Generated by Django 3.2.8 on 2021-10-12 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bids_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='auction_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bids',
            name='bid_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
