# Generated by Django 3.2.8 on 2021-10-12 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211012_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='auction_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
